version: '3'
services:
  psiturk:
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/psiturk/autoFR/google-credentials/credentials.json
    build: .
    ports:
     - 22362:22362
    volumes:
     - ./exp:/psiturk
    tty: true
    stdin_open: true
    restart: always
